// archive/src/components/ProfileScreen.vue
<script setup lang="ts">
import {computed, ref, watch} from 'vue';
import {
  Bed,
  Bus,
  Car,
  Clock3,
  Coffee,
  Edit3,
  ListChecks,
  MapPin,
  Pill,
  Plane,
  Save,
  SquarePen,
  Timer,
  Train,
  Trash2,
} from 'lucide-vue-next';
import type {TransportMode} from '@/types';
import {useTripStore} from '@/store/tripStore';

const {
  tripList,
  selectedTrip,
  selectTrip,
  updateTrip,
  upsertTripEvent,
  upsertPackingItem,
  togglePackingItem,
  removePackingItem,
} = useTripStore();

const tripTitle = ref('');
const originCity = ref('');
const destinationCity = ref('');
const departureTime = ref('09:30');
const arrivalTime = ref('14:15');
const hotel = ref('樱花皇宫大酒店');
const note = ref('');
const activeTransport = ref<TransportMode>('flight');
const newPackingItem = ref('');
const saveState = ref<'idle' | 'saved'>('idle');

const transportModes: Array<{
  id: TransportMode;
  label: string;
  icon: unknown;
  activeClass: string;
}> = [
  {id: 'flight', label: '飞机', icon: Plane, activeClass: 'border-primary bg-primary-fixed text-primary shadow-[0_4px_12px_rgba(224,64,160,0.15)]'},
  {id: 'train', label: '火车', icon: Train, activeClass: 'border-secondary bg-secondary-fixed text-secondary shadow-[0_4px_12px_rgba(124,82,170,0.15)]'},
  {id: 'bus', label: '巴士', icon: Bus, activeClass: 'border-tertiary bg-tertiary-fixed text-tertiary shadow-[0_4px_12px_rgba(0,150,204,0.15)]'},
  {id: 'car', label: '自驾', icon: Car, activeClass: 'border-primary-container bg-primary-fixed-dim text-primary'},
];

const primaryTransportEvent = computed(() => {
  return selectedTrip.value?.events.find((event) => event.eventType === 'transport') ?? null;
});

const packingItems = computed(() => selectedTrip.value?.packingItems ?? []);

watch(
  selectedTrip,
  (trip) => {
    if (!trip) {
      return;
    }

    tripTitle.value = trip.title;
    originCity.value = trip.originCity;
    destinationCity.value = trip.destinationCity;
    hotel.value = trip.hotelName;
    note.value = trip.note;
    activeTransport.value = trip.primaryTransportMode;
    departureTime.value = primaryTransportEvent.value?.startAt.slice(11, 16) ?? '09:30';
    arrivalTime.value = primaryTransportEvent.value?.endAt?.slice(11, 16) ?? '14:15';
    saveState.value = 'idle';
  },
  {immediate: true},
);

const saveTrip = () => {
  if (!selectedTrip.value) {
    return;
  }

  updateTrip(selectedTrip.value.id, {
    title: tripTitle.value.trim() || '新的旅行计划',
    originCity: originCity.value.trim() || selectedTrip.value.originCity,
    destinationCity: destinationCity.value.trim() || selectedTrip.value.destinationCity,
    hotelName: hotel.value.trim(),
    note: note.value.trim(),
    primaryTransportMode: activeTransport.value,
  });

  if (primaryTransportEvent.value) {
    upsertTripEvent(selectedTrip.value.id, {
      id: primaryTransportEvent.value.id,
      tripDayId: primaryTransportEvent.value.tripDayId,
      eventType: primaryTransportEvent.value.eventType,
      title: primaryTransportEvent.value.title,
      description: primaryTransportEvent.value.description,
      startAt: `${primaryTransportEvent.value.startAt.slice(0, 10)}T${departureTime.value}:00.000Z`,
      endAt: `${primaryTransportEvent.value.startAt.slice(0, 10)}T${arrivalTime.value}:00.000Z`,
      locationName: primaryTransportEvent.value.locationName,
      address: primaryTransportEvent.value.address,
      transportMode: activeTransport.value,
      referenceCode: primaryTransportEvent.value.referenceCode,
      source: primaryTransportEvent.value.source,
      status: primaryTransportEvent.value.status,
      meta: primaryTransportEvent.value.meta,
    });
  }

  saveState.value = 'saved';
};

const addPackingItem = () => {
  if (!selectedTrip.value || !newPackingItem.value.trim()) {
    return;
  }

  upsertPackingItem(selectedTrip.value.id, {
    label: newPackingItem.value.trim(),
    checked: false,
    category: 'other',
    source: 'manual',
    sortOrder: packingItems.value.length,
  });
  newPackingItem.value = '';
  saveState.value = 'idle';
};
</script>

<template>
  <div class="space-y-6 pb-24">
    <section class="rounded-3xl bg-white p-4 shadow-[0_8px_24px_rgba(224,64,160,0.08)]">
      <div class="flex items-center justify-between gap-4">
        <div>
          <p class="text-xs font-bold uppercase tracking-[0.2em] text-primary/70">当前编辑</p>
          <h2 class="mt-1 text-2xl font-black text-zinc-900">{{ selectedTrip?.title ?? '未选择行程' }}</h2>
        </div>
        <select
          :value="selectedTrip?.id"
          class="rounded-2xl border border-pink-100 bg-rose-50 px-4 py-3 text-sm font-semibold text-zinc-900 focus:border-primary focus:outline-none"
          @change="selectTrip(($event.target as HTMLSelectElement).value)"
        >
          <option v-for="trip in tripList" :key="trip.id" :value="trip.id">
            {{ trip.title }}
          </option>
        </select>
      </div>
    </section>

    <section class="group relative">
      <div class="absolute -inset-1 rounded-2xl bg-gradient-to-r from-primary to-secondary opacity-10 blur transition duration-1000 group-hover:opacity-20" />
      <div class="relative rounded-2xl bg-white p-6 shadow-[0_8px_32px_rgba(224,64,160,0.08)]">
        <label class="mb-2 block px-1 text-sm font-bold text-primary">行程标题</label>
        <div class="flex items-center gap-3 rounded-full border-2 border-transparent bg-surface-variant/50 px-5 py-3 transition-all focus-within:border-primary">
          <SquarePen :size="20" class="text-tertiary" />
          <input
            v-model="tripTitle"
            class="w-full border-none bg-transparent font-bold text-zinc-900 placeholder:text-outline-variant focus:ring-0"
            placeholder="给这次行程起个名字"
            type="text"
          >
        </div>
      </div>
    </section>

    <section class="grid grid-cols-2 gap-4">
      <div class="rounded-2xl bg-white p-4 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
        <label class="mb-2 block text-[11px] font-bold uppercase tracking-widest text-primary">出发城市</label>
        <div class="flex items-center gap-2 text-zinc-900">
          <MapPin :size="16" class="text-primary" />
          <input v-model="originCity" class="w-full border-none bg-transparent p-0 font-bold focus:ring-0" type="text">
        </div>
      </div>
      <div class="rounded-2xl bg-white p-4 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
        <label class="mb-2 block text-[11px] font-bold uppercase tracking-widest text-tertiary">目的地</label>
        <div class="flex items-center gap-2 text-zinc-900">
          <MapPin :size="16" class="text-tertiary" />
          <input v-model="destinationCity" class="w-full border-none bg-transparent p-0 font-bold focus:ring-0" type="text">
        </div>
      </div>
    </section>

    <section class="space-y-3">
      <h2 class="flex items-center gap-2 px-2 text-lg font-bold text-zinc-900">
        <Plane :size="20" class="text-secondary" />
        如何抵达？
      </h2>
      <div class="grid grid-cols-4 gap-3">
        <button
          v-for="mode in transportModes"
          :key="mode.id"
          type="button"
          class="bouncy-hover flex flex-col items-center gap-2 rounded-2xl border-2 p-4 transition-all"
          :class="activeTransport === mode.id ? ['scale-105', mode.activeClass] : 'border-transparent bg-white text-outline shadow-[0_4px_12px_rgba(0,0,0,0.05)]'"
          @click="activeTransport = mode.id"
        >
          <component :is="mode.icon" :size="28" />
          <span class="text-[10px] font-bold uppercase tracking-wider">{{ mode.label }}</span>
        </button>
      </div>
    </section>

    <section class="grid grid-cols-2 gap-4">
      <div class="rounded-2xl bg-white p-4 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
        <label class="mb-2 block text-[11px] font-bold uppercase tracking-widest text-secondary">出发</label>
        <div class="flex items-center gap-2 text-zinc-900">
          <Clock3 :size="16" class="text-secondary" />
          <input v-model="departureTime" class="w-full border-none bg-transparent p-0 font-bold focus:ring-0" type="time">
        </div>
      </div>
      <div class="rounded-2xl bg-white p-4 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
        <label class="mb-2 block text-[11px] font-bold uppercase tracking-widest text-tertiary">到达</label>
        <div class="flex items-center gap-2 text-zinc-900">
          <Timer :size="16" class="text-tertiary" />
          <input v-model="arrivalTime" class="w-full border-none bg-transparent p-0 font-bold focus:ring-0" type="time">
        </div>
      </div>
    </section>

    <section class="rounded-2xl bg-secondary-container p-6 shadow-[0_8px_24px_rgba(124,82,170,0.1)]">
      <h2 class="mb-4 flex items-center gap-2 text-sm font-bold text-secondary">
        <Bed :size="18" />
        入住酒店
      </h2>
      <div class="rounded-2xl border border-white bg-white/60 p-4 backdrop-blur-sm">
        <input
          v-model="hotel"
          class="w-full border-none bg-transparent font-medium text-zinc-800 placeholder:text-secondary-fixed-dim focus:ring-0"
          placeholder="酒店名称或地址..."
          type="text"
        >
      </div>
    </section>

    <section class="space-y-3">
      <h2 class="flex items-center gap-2 px-2 text-lg font-bold text-zinc-900">
        <ListChecks :size="20" class="text-primary" />
        准备好了吗？
      </h2>
      <div class="grid grid-cols-12 gap-3">
        <div class="col-span-7 rounded-2xl bg-white p-4 shadow-[0_4px_16px_rgba(0,0,0,0.04)]">
          <div class="space-y-3">
            <label v-for="item in packingItems" :key="item.id" class="group flex cursor-pointer items-center gap-3">
              <input :checked="item.checked" class="h-5 w-5 rounded-full text-primary transition-all focus:ring-primary" type="checkbox" @change="selectedTrip && togglePackingItem(selectedTrip.id, item.id)">
              <span class="flex-1 text-sm font-medium text-zinc-800 transition-colors group-hover:text-primary">{{ item.label }}</span>
              <button class="rounded-full bg-rose-50 p-2 text-rose-600" type="button" @click="selectedTrip && removePackingItem(selectedTrip.id, item.id)">
                <Trash2 :size="14" />
              </button>
            </label>
          </div>
          <div class="mt-4 flex gap-2">
            <input v-model="newPackingItem" class="flex-1 rounded-full border border-pink-100 bg-rose-50 px-4 py-2 text-sm focus:border-primary focus:outline-none" placeholder="新增清单项" type="text">
            <button class="rounded-full bg-primary px-4 py-2 text-sm font-bold text-white" type="button" @click="addPackingItem">
              添加
            </button>
          </div>
        </div>
        <div class="col-span-5 flex flex-col gap-3">
          <div class="bouncy-hover flex flex-1 flex-col items-center justify-center rounded-2xl bg-tertiary-fixed p-4 text-center">
            <Coffee :size="20" class="mb-1 text-tertiary" />
            <span class="text-[10px] font-bold uppercase text-tertiary">零食</span>
          </div>
          <div class="bouncy-hover flex flex-1 flex-col items-center justify-center rounded-2xl bg-primary-fixed p-4 text-center">
            <Pill :size="20" class="mb-1 text-primary" />
            <span class="text-[10px] font-bold uppercase text-primary">药品</span>
          </div>
        </div>
      </div>
    </section>

    <section class="rounded-2xl bg-white p-6 shadow-[0_8px_32px_rgba(0,0,0,0.04)]">
      <label class="mb-3 flex items-center gap-2 text-sm font-bold text-outline">
        <Edit3 :size="14" />
        旅行笔记
      </label>
      <textarea
        v-model="note"
        class="w-full resize-none rounded-2xl border-none bg-surface-variant/50 p-4 text-sm font-medium text-zinc-800 focus:ring-2 focus:ring-primary/20"
        placeholder="别忘了带雨伞，预约代码是 #12345..."
        rows="3"
      />
    </section>

    <div class="pb-8 pt-4">
      <button class="bouncy-hover candy-shadow-primary flex w-full items-center justify-center gap-3 rounded-full bg-primary py-5 text-lg font-black text-white" type="button" @click="saveTrip">
        <Save :size="24" />
        {{ saveState === 'saved' ? '已保存到本地计划' : '保存计划' }}
      </button>
    </div>
  </div>
</template>

// src/components/ProfileScreen.tsx
import React from 'react';
import { MapPin, Plane, Train, Bus, Car, Clock, Timer, Bed, ListChecks, Edit3, Save, Camera, Smartphone, BookOpen, Coffee, Pill } from 'lucide-react';
import { motion } from 'motion/react';

export const ProfileScreen: React.FC = () => {
  return (
    <div className="space-y-6 pb-24">
      {/* Hero Input: Destination */}
      <section className="relative group">
        <div className="absolute -inset-1 bg-gradient-to-r from-primary to-secondary rounded-2xl blur opacity-10 group-hover:opacity-20 transition duration-1000"></div>
        <div className="relative bg-white rounded-2xl p-6 shadow-[0_8px_32px_rgba(224,64,160,0.08)]">
          <label className="block text-primary font-bold text-sm mb-2 px-1">下一站去哪？</label>
          <div className="flex items-center gap-3 bg-surface-variant/50 rounded-full px-5 py-3 border-2 border-transparent focus-within:border-primary transition-all">
            <MapPin size={20} className="text-tertiary" />
            <input 
              className="bg-transparent border-none focus:ring-0 w-full font-bold text-zinc-900 placeholder:text-outline-variant" 
              placeholder="梦想目的地" 
              type="text" 
              defaultValue="京都樱花之旅"
            />
          </div>
        </div>
      </section>

      {/* Transportation Selection */}
      <section className="space-y-3">
        <h2 className="text-zinc-900 font-bold text-lg px-2 flex items-center gap-2">
          <Plane size={20} className="text-secondary" />
          如何抵达？
        </h2>
        <div className="grid grid-cols-4 gap-3">
          {[
            { label: '飞机', icon: Plane, active: true, color: 'primary' },
            { label: '火车', icon: Train, active: false, color: 'secondary' },
            { label: '巴士', icon: Bus, active: false, color: 'tertiary' },
            { label: '自驾', icon: Car, active: false, color: 'primary-container' },
          ].map((mode, i) => (
            <button 
              key={i}
              className={`flex flex-col items-center gap-2 p-4 rounded-2xl transition-all bouncy-hover ${
                mode.active 
                  ? `bg-primary-fixed border-2 border-primary shadow-[0_4px_12px_rgba(224,64,160,0.15)] scale-105` 
                  : 'bg-white shadow-[0_4px_12px_rgba(0,0,0,0.05)]'
              }`}
            >
              <mode.icon size={28} className={mode.active ? 'text-primary' : 'text-outline'} />
              <span className={`text-[10px] font-bold uppercase tracking-wider ${mode.active ? 'text-primary' : 'text-outline'}`}>
                {mode.label}
              </span>
            </button>
          ))}
        </div>
      </section>

      {/* Time Pickers */}
      <section className="grid grid-cols-2 gap-4">
        <div className="bg-white rounded-2xl p-4 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
          <label className="block text-secondary font-bold text-[11px] mb-2 uppercase tracking-widest">出发</label>
          <div className="flex items-center gap-2 text-zinc-900">
            <Clock size={16} className="text-secondary" />
            <input className="border-none p-0 focus:ring-0 font-bold bg-transparent w-full" type="time" defaultValue="09:30"/>
          </div>
        </div>
        <div className="bg-white rounded-2xl p-4 shadow-[0_4px_12px_rgba(0,0,0,0.05)]">
          <label className="block text-tertiary font-bold text-[11px] mb-2 uppercase tracking-widest">到达</label>
          <div className="flex items-center gap-2 text-zinc-900">
            <Timer size={16} className="text-tertiary" />
            <input className="border-none p-0 focus:ring-0 font-bold bg-transparent w-full" type="time" defaultValue="14:15"/>
          </div>
        </div>
      </section>

      {/* Accommodation */}
      <section className="bg-secondary-container rounded-2xl p-6 shadow-[0_8px_24px_rgba(124,82,170,0.1)]">
        <h2 className="text-secondary font-bold text-sm mb-4 flex items-center gap-2">
          <Bed size={18} />
          入住酒店
        </h2>
        <div className="bg-white/60 backdrop-blur-sm rounded-2xl p-4 border border-white">
          <input 
            className="w-full bg-transparent border-none focus:ring-0 font-medium placeholder:text-secondary-fixed-dim text-zinc-800" 
            placeholder="酒店名称或地址..." 
            type="text" 
            defaultValue="樱花皇宫大酒店"
          />
        </div>
      </section>

      {/* Packing Checklist */}
      <section className="space-y-3">
        <h2 className="text-zinc-900 font-bold text-lg px-2 flex items-center gap-2">
          <ListChecks size={20} className="text-primary" />
          准备好了吗？
        </h2>
        <div className="grid grid-cols-12 gap-3">
          <div className="col-span-7 bg-white rounded-2xl p-4 shadow-[0_4px_16px_rgba(0,0,0,0.04)]">
            <div className="space-y-3">
              {[
                { label: '相机与镜头', checked: true },
                { label: '便携式充电器', checked: false },
                { label: '护照', checked: true },
              ].map((item, i) => (
                <label key={i} className="flex items-center gap-3 cursor-pointer group">
                  <input 
                    type="checkbox" 
                    defaultChecked={item.checked}
                    className="rounded-full text-primary focus:ring-primary h-5 w-5 transition-all" 
                  />
                  <span className="text-sm font-medium group-hover:text-primary transition-colors text-zinc-800">{item.label}</span>
                </label>
              ))}
            </div>
          </div>
          <div className="col-span-5 flex flex-col gap-3">
            <div className="flex-1 bg-tertiary-fixed rounded-2xl p-4 flex flex-col items-center justify-center text-center bouncy-hover">
              <Coffee size={20} className="text-tertiary mb-1" />
              <span className="text-[10px] font-bold text-tertiary uppercase">零食</span>
            </div>
            <div className="flex-1 bg-primary-fixed rounded-2xl p-4 flex flex-col items-center justify-center text-center bouncy-hover">
              <Pill size={20} className="text-primary mb-1" />
              <span className="text-[10px] font-bold text-primary uppercase">药品</span>
            </div>
          </div>
        </div>
      </section>

      {/* Memo Section */}
      <section className="bg-white rounded-2xl p-6 shadow-[0_8px_32px_rgba(0,0,0,0.04)]">
        <label className="flex items-center gap-2 text-outline font-bold text-sm mb-3">
          <Edit3 size={14} />
          旅行笔记
        </label>
        <textarea 
          className="w-full bg-surface-variant/50 rounded-2xl border-none focus:ring-2 focus:ring-primary/20 text-sm font-medium p-4 resize-none text-zinc-800" 
          placeholder="别忘了带雨伞，预约代码是 #12345..." 
          rows={3}
        />
      </section>

      {/* Save Button */}
      <div className="pt-4 pb-8">
        <button className="w-full py-5 bg-primary rounded-full candy-shadow-primary bouncy-hover flex items-center justify-center gap-3 text-white font-black text-lg">
          <Save size={24} />
          保存计划
        </button>
      </div>
    </div>
  );
};
